# simple server tasks
---

- name: create apps directory
  file: path=/home/deploy/apps/{{app_name}}/shared state=directory
  become: true
  become_user: deploy

- name: copy .env file
  copy: src=.env.{{ deploy_env }} dest=/home/deploy/apps/{{app_name}}/shared/.env.production decrypt=yes
  become: true
  become_user: deploy

- name: Install wkhtmltopdf from the GitHub released version
  apt:
    deb: https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb